### ISSUE TITLE
Consider adding a custom codec (`#coding: record`?) to allow use of `struct/record RecordName(...)` syntax directly.

### ISSUE THREAD

**Issue by Sachaa-Thanasius** [brettcannon/record-type#7]
This is just an idea; maybe providing a custom codec that, when registered, allows `struct RecordName(...)` to be interpreted as valid Python code would give a better visual of "structs" or "records" as a potential built-in part of Python (for those willing to try it out, of course). Not the easiest thing in the world for regular users to test out proposed but currently nonexistent syntax, from what I can tell, so this is one way to allow that.

Also, I was curious if it was possible, so I did it myself for fun. It isn't perfect and explicitly only uses `struct`, but I hope it shows what I mean.

https://github.com/Sachaa-Thanasius/record-type/blob/faster/record_type/_codec.py
https://github.com/Sachaa-Thanasius/record-type/blob/faster/examples/example_with_codec.py

**Comment by brettcannon** [comment]
Thanks for the idea! It's definitely possible, but at the moment I don't plan to pursue a syntax proposal based on the feedback I got on Mastodon for the iddea.

**Comment by Sachaa-Thanasius** [comment]
Ah, I wasn’t aware of that. Fair enough.
